# Generated by Django 5.0.2 on 2024-03-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_handling', '0006_contactinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='zip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
