# Generated by Django 5.0.2 on 2024-03-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_handling', '0011_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.FileField(blank=True, default='profile_pic.png', upload_to='profile_pics'),
        ),
    ]
