# Generated by Django 5.0.2 on 2024-03-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_handling', '0012_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.FileField(blank=True, upload_to='profile_pics'),
        ),
    ]
