# Generated by Django 5.0.2 on 2024-04-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_handling', '0016_geek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geek',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
