# Generated by Django 5.0.2 on 2024-04-06 04:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_handling', '0017_alter_geek_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geek',
            name='slug',
        ),
        migrations.AddField(
            model_name='geek',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='geek_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
